fix: improve error handle of scripts. Add capability to run or not based on last runtime

diff --git a/append/usr/local/sbin/checkfiles b/append/usr/local/sbin/checkfiles
--- a/append/usr/local/sbin/checkfiles
+++ b/append/usr/local/sbin/checkfiles
@@ -3,12 +3,12 @@
 if [ -f "$(dirname $0)/dsas_common.sh" ]; then
   . $(dirname $0)/dsas_common.sh
 else
-  echo "Common functions not found !!"
+  1>&2 echo "Common functions not found !!"
   exit -1
 fi
 
 # Default options
-logfile="$(dirname $CONF)/verif.log"
+logfile="$(dirname $CONF)/dsas_verif.log"
 UMASK=640
 
 help() {
@@ -73,7 +73,7 @@ verifdirectory() {
   # Validate check type
   case $type in
     authenticode|openssl|gpg) : ;;
-    *) 1>&2 echo "Unknown file checking type"; return 1 ;;
+    *) 1>&2 echo "Unknown file checking type"; exit 1 ;;
   esac
 
   tempdir=$(mktemp -d)
@@ -83,10 +83,7 @@ verifdirectory() {
     fprint=$(xmllint --xpath "string(dsas/tasks/task[$id]/cert[$j]/fingerprint)" $CONF)
     [ -z "$fprint" ] && break;
     idx=$(get_certificate $fprint)
-    if [ -z "$idx" ]; then
-      echo "Certificate used by task($id) not found !!"
-      return
-    fi
+    [ -z "$idx" ] && { 1>&2 echo "Certificate used by task($id) not found !!"; exit 1; }
     if [ $idx -eq 0 ]; then
       [ -f "$tempdir/cert.0" ] && myecho "Multiple authority certificates defined" 
       /bin/mv /tmp/cert.$$ $tempdir/cert.0
@@ -113,8 +110,8 @@ verifdirectory() {
   filetable=$(ls -1 $DSAS_HAUT/$dir)
   for file in $(cd $DSAS_BAS/$dir; find . -type f); do
     if [[ "$filetable" != *"${file:2}"* ]]; then
-      echo "Removing stale file ${file:2}"
-      rm $DSAS_BAS/$dir/${file:2}
+      myecho "Removing stale file ${file:2}"
+      /bin/rm -f $DSAS_BAS/$dir/${file:2}
     fi
   done
 
@@ -186,10 +183,7 @@ verifrepo() {
   tempdir=$(mktemp -d)
   fprint=$(xmllint --xpath "string(dsas/tasks/task[$id]/cert[1]/fingerprint)" $CONF)
   idx=$(get_certificate $fprint)
-  if [ -z "$idx" ]; then
-    echo "Certificate used by task($id) not found !!"
-    return
-  fi
+  [ -z "$idx" ] && { 1>&2 echo "Certificate used by task($id) not found !!"; exit 1; }
   /bin/mv /tmp/cert.$$ $tempdir/cert.0
   gpg --dearmor $tempdir/cert.0
 
@@ -199,8 +193,8 @@ verifrepo() {
     if ! gpg --no-default-keyring --keyring $tempdir/cert.0.gpg  \
           --verify $DSAS_HAUT/$dir/repodata/repomd.xml.asc \
           $DSAS_HAUT/$dir/repodata/repomd.xml 2>&1 1> /dev/null; then
-      echo "Failed to verify repomd.xml signature"
-      return 1
+      1>&2 echo "Failed to verify repomd.xml signature"
+      exit 1
     fi
   else
     # For rpm signature verification need to import GPG key
@@ -226,7 +220,7 @@ verifrepo() {
          xmllint --xpath 'string(//repomd/data[@type="primary"]/checksum/@type)' - )
   if  check_checksum $DSAS_HAUT/$dir/$filelist $chksum $chktype; then
     1>&2 echo "Error verifiying checksum of $filelist"
-    return
+    exit 1
   fi
 
   # Unzip and verify the checksum of primary.xml
@@ -240,7 +234,7 @@ verifrepo() {
   gunzip -k -f $DSAS_HAUT/$dir//$filelist
   if  check_checksum $DSAS_HAUT/$dir/$unzipfile $chksum $chktype; then
     1>&2 echo "Error verifiying checksum of $unzipfile"
-    return
+    exit 1
   fi
 
   # Copy repomd.xml*  and primary.xml* to $bas
@@ -259,8 +253,8 @@ verifrepo() {
   # Remove the files in $DSAS_BAS and not listed in primary.xml
   for _file in $(cd $DSAS_BAS/$dir; find . -path ./repodata -prune -type f -o -type f); do
     if [[ "$filetable" != *"${_file:2}"* ]]; then
-      echo "Removing stale file ${_file:2}"
-      rm $DSAS_BAS/$dir/${_file:2}
+      myecho "Removing stale file ${_file:2}"
+      /bin/rm -f $DSAS_BAS/$dir/${_file:2}
     fi
   done
 
@@ -286,8 +280,8 @@ passdirectory(){
   filetable=$(ls -1 $DSAS_HAUT/$dir)
   for file in $(cd $DSAS_BAS/$dir; find . -type f); do
     if [[ "$filetable" != *"${file:2}"* ]]; then
-      echo "Removing stale file ${file:2}"
-      rm $DSAS_BAS/$dir/${file:2}
+      myecho "Removing stale file ${file:2}"
+      /bin/rm -f $DSAS_BAS/$dir/${file:2}
     fi
   done
 
@@ -317,7 +311,10 @@ while [ "$#" -gt 0 ]; do
     --out=*) logfile=${1#*=} ;;
     -?|-h|--help) help; exit 0 ;;
     -*) 1>&2 echo "Unrecognized option : $1"; help; exit 1 ;;
-    *) ids="$ids $1" ;;
+    *) 
+      [ -n "$ids" ] && { 1>&2 echo "Only a single task is allowed"; exit 1; }
+      ids="$ids $1" 
+      ;;
   esac
   shift 1
 done
@@ -328,9 +325,8 @@ done
 # Check that all ids are valid before doing anything
 idx=""
 for _id in $ids; do
-  task_id_to_idx $_id
-  _idx=$?
-  [ $_idx -lt 1 ] && (echo "Task id ($_id) does not exist"; exit -1)
+  _idx=$(task_id_to_idx $_id)
+  [ $? -ne 0 ] && { 1>&2 echo "Task id ($_id) does not exist"; exit 1; }
   idx="$idx $_idx"
 done
 
@@ -342,9 +338,9 @@ for _id in $idx; do
     type=$(xmllint --xpath "string(dsas/tasks/task[$_id]/type)" $CONF)
     case $type in
       rpm|repomd) verifrepo $_id; ;;
-      deb) echo "DEB files are  are not yet implemented"; continue; ;;
+      deb) 1>&2 echo "DEB files are  are not yet implemented"; exit 1; ;;
       authenticode|openssl|gpg) verifdirectory $_id; ;; 
-      *) echo "Unknown task type : $type"; ;;
+      *) 1>&2 echo "Unknown task type : $type"; exit 1 ;;
     esac
   fi
 done
diff --git a/append/usr/local/sbin/getfiles b/append/usr/local/sbin/getfiles
--- a/append/usr/local/sbin/getfiles
+++ b/append/usr/local/sbin/getfiles
@@ -3,7 +3,7 @@
 if [ -f "$(dirname $0)/dsas_common.sh" ]; then
   . $(dirname $0)/dsas_common.sh
 else
-  echo "Common functions not found !!"
+  1>&2 echo "Common functions not found !!"
   exit -1
 fi
 
@@ -14,8 +14,8 @@ getdirectory() {
   local dir=$(xmllint --xpath "string(dsas/tasks/task[$id]/directory)" $CONF)
   local name=$(xmllint --xpath "string(dsas/tasks/task[$id]/name)" $CONF)
 
-
   if [ -z "$uri" ]; then
+    # The URI can be empty. gracefully exit
     myecho "Empty Uri for task $name"
     return
   fi
@@ -29,7 +29,8 @@ getdirectory() {
     myecho "Downloading file: $(basename $uri)"
     get "${uri}" "${DSAS_HAUT}/${dir}/${basename $uri}"
   else
-    files=$(get_dirlist $uri)
+    myecho "Downloading directory listing : $uri"
+    files=$(get_dirlist $uri) || { 1>&2 echo "error fetching directory listing"; exit 1; }
 
     # Remove files locally that are no longer available sur le URI
     for file in $(ls -1 $DSAS_HAUT/$dir); do
@@ -38,7 +39,7 @@ getdirectory() {
       
       if [[ "$files" != *"$file"* ]]; then
         myecho "Removing stale file: $file"
-        rm $DSAS_HAUT/$dir/$file
+        /bin/rm -f $DSAS_HAUT/$dir/$file
       fi
     done
 
@@ -122,8 +123,8 @@ getrepo() {
          sed -e "s:repomd xmlns:repomd ignore:g" | \
          xmllint --xpath 'string(//repomd/data[@type="primary"]/checksum/@type)' - )
        if  check_checksum $DSAS_HAUT/$dir/$filelist $chksum $chktype; then
-         2>1 echo "Error verifying checksum of $filelist"
-         return
+         1>&2 echo "Error verifying checksum of $filelist"
+         exit 1
        fi
 
        # Unzip and verify the checksum of primary.xml
@@ -136,8 +137,8 @@ getrepo() {
        unzipfile=$(echo $filelist | sed -e "s/.gz//g")
        gunzip -k -f $DSAS_HAUT/$dir/$filelist
        if  check_checksum $DSAS_HAUT/$dir/$unzipfile $chksum $chktype; then
-         2>1 echo "Error verifying checksum of $unzipfile"
-         return
+         1>&2 echo "Error verifying checksum of $unzipfile"
+         exit 1
        fi
 
        # Recover a table of the hashtype, hash and file names
@@ -151,20 +152,20 @@ getrepo() {
        for _file in $(cd $DSAS_HAUT/$dir; find . -path ./repodata -prune -type f -o -type f); do
          if [[ "$filetable" != *"${_file:2}"* ]]; then
            myecho "Removing stale file ${_file:2}"
-           rm $DSAS_HAUT/$dir/${_file:2}
+           /bin/rm -f $DSAS_HAUT/$dir/${_file:2}
          fi
        done
 
        # Download the packages
        get_packages "$DSAS_HAUT/$dir" $uri $filetable
        ;;
-    *) echo "Unrecognized repositiory check type $check"; ;;
+    *) 1>&2 echo "Unrecognized repositiory check type $check"; exit 1; ;;
   esac
 }
 
 help() {
-  echo "Usage: $(basename $0)  [Options] ID [ID...]"
-  echo "Get files given by the task ID(s)"
+  echo "Usage: $(basename $0)  [Options] ID"
+  echo "Get files given by the task ID"
   echo "     -v|--verbose    Log all files verified"
   echo "     -q|--quiet      Log only files failing to verifiy"
   echo "     -n|--dryrun     Perform no actions"
@@ -182,7 +183,10 @@ while [ "$#" -gt 0 ]; do
     -n|--dryrun) dryrun=1 ;;
     -?|-h|--help) help; exit 0 ;;
     -*) 1>&2 echo "Unrecognized option : $1"; help; exit 1 ;;
-    *) ids="$ids $1" ;;
+     *)
+       # Only allow a single task to be able to exit en error correctly 
+       [ -n "$ids" ] && 1>&2 ecdo "Only a single task is allowed" && exit 1
+       ids="$ids $1" ;;
   esac
   shift 1
 done
@@ -193,9 +197,8 @@ done
 # Check that all ids are valid before doing anything
 idx=""
 for _id in $ids; do
-  task_id_to_idx $_id
-  _idx=$?
-  [ $_idx -lt 1 ] && (echo "Task id ($_id) does not exist"; exit -1)
+  _idx=$(task_id_to_idx $_id)
+  [ $? -ne 0 ] && { 1>&2 echo "Task id ($_id) does not exist"; exit 1; }
   idx="$idx $_idx"
 done
 
@@ -203,9 +206,9 @@ for _idx in $idx; do
   type=$(xmllint --xpath "string(dsas/tasks/task[$_idx]/type)" $CONF)
   case $type in
     rpm|repomd) getrepo $_idx; ;;
-    deb) echo "DEB files are not yet implemented"; continue; ;;
+    deb) 1>&2 echo "DEB files are not yet implemented"; exit 1; ;;
     authenticode|openssl|gpg) getdirectory $_idx; ;;
-    *) echo "Unknown task type : $type"; ;;
+    *) 1>&2 echo "Unknown task type : $type"; exit 1; ;;
   esac
 done
 
diff --git a/append/usr/local/sbin/runtask b/append/usr/local/sbin/runtask
--- a/append/usr/local/sbin/runtask
+++ b/append/usr/local/sbin/runtask
@@ -8,17 +8,90 @@ fi
 
 # if not user tc, quit
 if [ "$(whoami)" != "tc" ]; then
- 1>&2 echo "$0: Must e run as user 'tc'"
+ 1>&2 echo "$0: Must be run as user 'tc'"
 fi
 
 if [ -f "$(dirname $0)/dsas_common.sh" ]; then
   . $(dirname $0)/dsas_common.sh
 else
-  echo "Common functions not found !!"
+  1>&2 echo "Common functions not found !!"
   exit -1
 fi
 
-ssh tc@$INTERCO_HAUT sudo sudo -u haut $(dirname $0)/getfiles $*
-ssh tc@$INTERCO_HAUT sudo sudo -u verif $(dirname $0)/checkfiles $*
-sudo sudo -u haut $(dirname $0)/getfiles $*
-sudo sudo -u verif $(dirname $0)/checkfiles $*
+# Créate run log file if it doesn't exist
+[ -f "$RUNLOG" ] || touch $RUNLOG
+
+# Parse options
+ids=""
+opts=""
+force=""
+while [ "$#" -gt 0 ]; do
+  case $1 in
+    -f|--force) force="true"; ;;
+    -v|--verbose) verbose=1; opts="$opts -v"; ;;
+    -q|--quiet) verbose=0; opts="$opts -q"; ;;
+    -*) opts="$opts $1"; ;;
+     *) ids="$ids $1" ;;
+  esac
+  shift 1
+done
+
+if [ -z $ids ]; then
+  # No tasks sepcified. Get a list of all tasks
+  i=1
+  while :; do
+    _id=$(xmllint --xpath "string(dsas/tasks/task[$i]/id)" $CONF)
+    [ -z "$_id" ] && break
+    # Is the task scheduled to run ? Is the run forced ?
+    if [ -z "$force" ]; then
+      _run=$(xmllint --xpath "string(dsas/tasks/task[$i]/run)" $CONF)
+      _last=$(cat $RUNLOG | grep $_id | cut -d' ' -f2) 
+      [ -z "$_last" ] || should_run $_last $_run && ids="$ids $_id"    
+    else
+      ids="$ids $_id"
+    fi
+    i=$((i + 1))
+  done
+elif [ -z "$force" ]; then
+  # Delete the tasks not scheduled to run from the list
+  newids=""
+  for _id in $ids; do
+    i=1
+    while :; do
+      _idx=$(xmllint --xpath "string(dsas/tasks/task[$i]/id)" $CONF)
+      [ -z "$_idx" ] && break
+      [ "$_id" == "$_idx" ] && break     
+      i=$((i + 1))
+    done
+    [ -z "$_idx" ] && 1>&2 echo "Task $_id not found" && continue
+    _run=$(xmllint --xpath "string(dsas/tasks/task[$i]/run)" $CONF)
+    _last=$(cat $RUNLOG | grep $_id | cut -d' ' -f2)
+    [ -z "$_last" ] || should_run $_last $_run && newids="$newids $_id" 
+  done
+  ids=$newids
+fi
+
+LOG="$(dirname $CONF)/dsas_verif.log"
+[ -f "$LOG" ] || (umask 0007; touch $LOG; )
+chgrp verif $LOG
+
+[ -z "$ids" ] && myecho "No tasks to run !!"
+
+for _id in $ids; do
+  # Check if task is already running and skip if not 
+  _pid=$(pgrep $_id)
+  [ -n "$_pid" ] && 2>&1 echo "task $_id is running" && continue
+
+  myecho "#### Tasks on machine HAUT ####"
+  ssh tc@$INTERCO_HAUT sudo sudo -u haut $(dirname $0)/getfiles $opts $_id
+  [ $? -eq 0 ] && ssh tc@$INTERCO_HAUT sudo sudo -u verif $(dirname $0)/checkfiles $opts $_id
+  [ $? -eq 0 ] && myecho "#### Tasks on machine BAS ####"
+  [ $? -eq 0 ] && sudo sudo -u haut $(dirname $0)/getfiles $opts $_id
+  [ $? -eq 0 ] && sudo sudo -u verif $(dirname $0)/checkfiles $opts -o $LOG $_id
+
+  # Log the run date and exit status of the task
+  _str=$(printf "%-26s %-16s %d" "$_id" "$(utc_date)" $?)
+  grep -q $_id $RUNLOG && sed -e "s/^$_id.*$/$_str/" $RUNLOG > $RUNLOG 
+  grep -q $_id $RUNLOG || echo $_str >> $RUNLOG
+
+done
