feat: Start on integration of task treatment

diff --git a/append/usr/local/sbin/checkfiles b/append/usr/local/sbin/checkfiles
--- a/append/usr/local/sbin/checkfiles
+++ b/append/usr/local/sbin/checkfiles
@@ -1,66 +1,32 @@
 #! /bin/sh
 
-cd $(dirname $0)
+if [ -f "usr/local/sbin/dsas_common.sh" ]; then
+  . /usr/local/share/sbin/dsas_common.sh
+elif [ -f "/home/tc/dsas---tinycore/append/usr/local/sbin/dsas_common.sh" ]; then
+  # FIXME For testing purposes. Delete ?
+  . /home/tc/dsas---tinycore/append/usr/local/sbin/dsas_common.sh
+else
+  echo "Common functions not found !!"
+  exit -1
+fi
 
-#### FIXME : Temporary directories for testing
-bas=/home/tc/dsas---tinycore/test/bas
-haut=/home/tc/dsas---tinycore/test/haut
-
-# XML Configuration file
-conf=/opt/dsas_conf.xml
-# FIXME for testing
-[ -f $conf ] || conf=/home/tc/dsas---tinycore/append/opt/dsas_conf.xml
 
 # Default options
-verbose=1
-movefiles=0
-deletebad=1
+
 logfile="verif.log"
-logstdout=0
-dryrun=0
 rotatemax=6
 rotate=0
 reject=reject
 UMASK=640
-grp=share
 
-msg() {
-  if [ $logstdout = "1" ]; then
-    printf "%-3s %-15s %-32s %s\n" "$1" "$2" "$3" "$4"
-  else
-    printf "%-3s %-15s %-32s %s\n" "$1" "$2" "$3" "$4" >> $logfile
-  fi
-}
-
-msgline() {
-  local file=$1
-  local status=$2
-  local md5=$(cat $file | md5sum | sed -e "s/  -$//g")
-  local _file=`echo $file | sed -e "s:^${haut}/::g"`
-  case $status in
-    0) [ $verbose == 1 ] && msg "  "  "Ok"  $md5 $_file ;;
-    -1)  msg "XX"  "Unknown type"   $md5  $_file ;;
-    1)   msg "**"  "Bad Sig"        $md5  $_file ;;
-    2)   msg "$$"  "Checksum fail"  $md5  $_file ;;
-    3)   msg "**"  "Bad Interm Sig" $md5  $_file ;;
-    4)   msg "**"  "Fail virus chk" $md5  $_file ;;
-    5)   msg "**"  "Bad RPM Sig"    $md5  $_file ;;
-    255) msg "**"  "Not signed"     $md5  $_file ;;
-    *)   msg "XX"  "Unknown status" $md5  $_file ;;
-  esac
-}
 
 help() {
-  echo "Usage: $(basename $0)  [Options] [NAME...]"
-  echo "Verify files given by NAME. Without NAME all repositories are checked "
+  echo "Usage: $(basename $0)  [Options] ID [ID...]"
+  echo "Verify files given by the task ID."
   echo "     -v|--verbose    Log all files verified"
   echo "     -q|--quiet      Log only files failing to verifiy"
   echo "     -r|--rotate     Rotate the log files"
   echo "     -n|--dryrun     Perform no actions"
-  echo "     -m|--move       Move files"
-  echo "     -x|--link       Leave files in place and hard-link"
-  echo "     -d|--delete     Delete files faling to verify"
-  echo "     -k|--keep       Keep all files"
   echo "     -s|--stdout     Send logs to stdout"
   echo "     -l|--log        Send the logs to a file"
   echo "     -o <FILE>       Log to <FILE>, default $logfile"
@@ -68,64 +34,10 @@ help() {
   echo "     -?|-h|--help    Print this help"
 }
 
-mv() {
-  if [ $dryrun == "0" ]; then
-    [ -d $(dirname $2) ] || ( mkdir -m 770 -p $(dirname $2); chgrp -R bas $(dirname $2))
-    # We can't can't the owner of the file as we aren't root. So a 
-    # move must be treated as a copy and delete
-    /bin/cp $1 $2
-    chgrp bas $2
-    /bin/rm $1
-  else
-    echo "[DryRun] mv $*"
-  fi
-}
-
-ln() {
-  if [ $dryrun == "0" ]; then
-    [ -d $(dirname $2) ] || ( mkdir -m 770 -p $(dirname $2); chgrp -R bas $(dirname $2))
-    # This script is not running as root so can't change the owner. We
-    # first have to copy the file
-    cp $1 $1.tmp.$$
-    /bin/mv -f $1.tmp.$$ $1
-    chmod 0640 $1
-    chgrp $grp $1
-    /bin/ln -f $* 
-  else
-    [ -d $(dirname $2) ] || echo "[DryRun] mkdir -p $(dirname $2)"
-    echo "[DryRun] ln $*"
-  fi
-}
-
-rm() {
-  if [ $dryrun == "0" ]; then
-    /bin/rm $*
-  else
-    echo "[DryRun] rm $*"
-  fi
-}
-
-move() {
-  if [ $movefiles == "1" ]; then
-    mv $*
-  else
-    ln $*
-  fi
-}
-
-treatbad() {
-  if [ $deletebad == "1" ]; then
-    rm "$*"
-  else
-    move "$*"
-  fi
-}
-
 rotatelogs() {
   [ -f "${logfile}.$rotatemax" ] && rm "${logfile}.$rotatemax"
   for i in $(seq $rotatemax -1 2); do
-    i1=$(echo "$i 1 - p" | dc)
-    [ -f "${logfile}.$i1" ] && mv "${logfile}.$i1" "${logfile}.$i"
+    [ -f "${logfile}.$((i-1))" ] && mv "${logfile}.$((i-1))" "${logfile}.$i"
   done
   [ -f "${logfile}" ] && mv "${logfile}" "${logfile}.1"
   exit 0
@@ -184,8 +96,8 @@ antivirus() {
 
 verifdirectory() {
   local id=$1
-  local dir=$(xmllint --xpath "string(dsas/tasks/task[@id='$id']/@dir)" $conf)
-  local check=$(xmllint --xpath "string(dsas/tasks/task[@id='$id']/check/@type)" $conf)
+  local dir=$(xmllint --xpath "string(dsas/tasks/task[$id]/directory)" $conf)
+  local check=$(xmllint --xpath "string(dsas/tasks/task[$id]/type)" $conf)
 
   # Validate check type
   case $check in
@@ -197,15 +109,13 @@ verifdirectory() {
   [ -d $bas/$dir ] || mkdir -p $bas/$dir
 
   # Remove the files in our tree $bas and not in $haut.
-  if [ "$deletebad" == "1" ]; then
-    filetable=$(ls -1 $haut/$dir)
-    for _file in $(cd $bas/$dir; find . -type f); do
-      if [[ "$filetable" != *"${_file:2}"* ]]; then
-        echo "Removing stale file ${_file:2}"
-        rm $bas/$dir/${_file:2}
-      fi
-    done
-  fi
+  filetable=$(ls -1 $haut/$dir)
+  for _file in $(cd $bas/$dir; find . -type f); do
+    if [[ "$filetable" != *"${_file:2}"* ]]; then
+      echo "Removing stale file ${_file:2}"
+      rm $bas/$dir/${_file:2}
+    fi
+  done
 
   ca=$(xmllint --xpath "string(dsas/tasks/task[@id='$id1']/cert[@type='ca'])" $conf)
   [ -z "$ca" ] || $(echo "$ca" > /tmp/tmpcert; ca="/tmp/tmpcert")
@@ -218,38 +128,12 @@ verifdirectory() {
     status=$?
     msgline $haut/$file $status
     case $status in
-      0) move "$haut/$file" "$bas/$file"; ;;
-      *) treatbad "$haut/$file" "$haut/$reject/$file"; ;;
+      0) ln "$haut/$file" "$bas/$file"; ;;
+      *) ln "$haut/$file" "$haut/$reject/$file"; ;;
     esac
   done
 
   [ -z "$ca" ] || /bin/rm /tmp/tmpcert
-}
-
-# Usage : check_checksum <file> <chksum> <type>
-check_checksum() {
-  case $3 in
-    sha512)
-      chk=$(cat $1 | sha512sum - | sed -e "s/ -//g")
-      ;;
-    sha256)
-      chk=$(cat $1 | sha256sum - | sed -e "s/ -//g")
-      ;;
-    sha)
-      chk=$(cat $1 | sha1sum - | sed -e "s/ -$//g")
-      ;;
-    md5)
-      chk=$(cat $1 | md5sum - | sed -e "s/ -$//g")
-      ;;
-    *)
-     return 0
-     ;;
-  esac
-
-  if [ $chk != $2 ]; then
-    return 0
-  fi
-  return 1
 }
 
 verify_packages() {
@@ -269,13 +153,13 @@ verify_packages() {
     if [ -f "$haut/$dir/$file" ]; then
       if  check_checksum $haut/$dir/$file $chksum $chktype; then
         msgline $haut/$dir/$file 1
-        treatbad $haut/$dir/$file $haut/$reject/$dir/$file
+        ln $haut/$dir/$file $haut/$reject/$dir/$file
       elif [ "$rpm_k" == "1" ] && rpm -K $haut/$dir/$file 2>&1 /dev/null; then
         msgline $haut/$dir/$file 5
-        treatbad $haut/$dir/$file $haut/$reject/$dir/$file       
+        ln $haut/$dir/$file $haut/$reject/$dir/$file       
       else
         msgline $haut/$dir/$file 0
-        move $haut/$dir/$file $bas/$dir/$file
+        ln $haut/$dir/$file $bas/$dir/$file
       fi
     fi  # For now ignore missing files
     shift 3
@@ -349,13 +233,13 @@ verifrepo() {
        fi
 
        # Copy repomd.xml*  and primary.xml* to $bas
-       move $haut/$dir/repodata/repomd.xml \
+       ln $haut/$dir/repodata/repomd.xml \
           $bas/$dir/repodata/repomd.xml
-       move $haut/$dir/repodata/repomd.xml.asc \
+       ln $haut/$dir/repodata/repomd.xml.asc \
           $bas/$dir/repodata/repomd.xml.asc
-       move $haut/$dir/$filelist \
+       ln $haut/$dir/$filelist \
           $bas/$dir/$filelist
-       move $haut/$dir/$unzipfile \
+       ln $haut/$dir/$unzipfile \
           $bas/$dir/$unzipfile
 
        # Recover a table of the hashtype, hash and file names
@@ -380,48 +264,45 @@ verifrepo() {
   esac
 }
 
-# Find the upper and lower zones
-[ -d /home/dsas/bas ] && bas=/home/dsas/bas
-[ -z $bas ] && [ -d /home/bas ] && bas=/home/bas
-[ -d /home/dsas/haut ] && haut=/home/dsas/haut
-[ -z $haut ] && [ -d /home/haut ] && haut=/home/haut
-[ -z $bas ] && $(1>&2 echo "Zone bas not found"; exit 1)
-[ -z $haut ] && $(1>&2 echo "Zone haut not found"; exit 1)
+check_dsas
 
 # Parse options
-names=""
+ids=""
 while [ "$#" -gt 0 ]; do
   case $1 in
     -v|--verbose) verbose=1 ;;
     -q|--quiet) verbose=0 ;;
     -r[--rotate) rotate=1 ;;
     -n|--dryrun) dryrun=1 ;;
-    -m|--move) movefiles=1 ;;
-    -x|--link) movefiles=0 ;;
-    -d|--delete) deletebad=1 ;;
-    -k|--keep) deletebad=0 ;;
     -s|--stdout) logstdout=1 ;;
     -l|--log) logstdout=0 ;;
     -o) logfile=$2; shift 1 ;;
     --out=*) logfile=${1#*=} ;;
     -?|-h|--help) help; exit 0 ;;
     -*) 1>&2 echo "Unrecognized option : $1"; help; exit 1 ;;
-    *) names="$names $1" ;;
+    *) ids="$ids $1" ;;
   esac
   shift 1
 done
 
-for _id in $(xmllint --xpath 'dsas/tasks/task/@id' $conf); do
-  eval $_id
-  type=$(xmllint --xpath "string(dsas/tasks/task[@id='$id']/@type)" $conf)
-  if [ "${#names}" -gt "0" ]; then
-    name=$(xmllint --xpath "string(dsas/tasks/task[@id='$id']/@name)" $conf)
-    [[ "$names" == *"$name"* ]] || continue
-  fi
+# If dryrun, force verbose
+[ $dryrun -ne 0 ] && verbose=1
+
+# Check that all ids are valid before doing anything
+idx=""
+for _id in $ids; do
+  task_id_to_idx $_id
+  _idx=$?
+  [ $_idx -lt 1 ] && (echo "Task id ($_id) does not exist"; exit -1)
+  idx="$idx $_idx"
+done
+
+for _id in idx; do
+  type=$(xmllint --xpath "string(dsas/tasks/task[$id]/type)" $conf)
   case $type in
-    linux)  verifrepo $id; ;;
-    directory) verifdirectory $id; ;;
+    rpm|repomd) verifrepo $id; ;;
+    deb) echo "DEB files are  are not yet implemented"; continue; ;;
+    authenticode|openssl|gpg) verifdirectory $id; ;; 
     *) echo "Unknown task type : $type"; ;;
   esac
 done
-
diff --git a/append/usr/local/sbin/getfiles b/append/usr/local/sbin/getfiles
--- a/append/usr/local/sbin/getfiles
+++ b/append/usr/local/sbin/getfiles
@@ -1,87 +1,65 @@
 #! /bin/sh
 
-#### FIXME : Temporary directories for testing
-haut=/home/tc/dsas---tinycore/test/haut
+if [ -f "usr/local/sbin/dsas_common.sh" ]; then
+  . /usr/local/share/sbin/dsas_common.sh
+elif [ -f "/home/tc/dsas---tinycore/append/usr/local/sbin/dsas_common.sh" ]; then
+  # FIXME For testing purposes. Delete ?
+  . /home/tc/dsas---tinycore/append/usr/local/sbin/dsas_common.sh
+else
+  echo "Common functions not found !!"
+  exit -1
+fi
 
-# XML Configuration file
-conf=/opt/dsas_conf.xml
-# FIXME for testing
-[ -f $conf ] || conf=/home/tc/dsas---tinycore/append/opt/dsas_conf.xml
-
-fileargs() {
-while [ "$#" -gt 3 ]; do
-  shift 3
-  echo $1
-  shift 1
-done
-}
 
 getdirectory() {
-  id=$1
-  uri=$2
-  clean=$(xmllint --xpath "string(dsas/tasks/task[@id='$id']/@clean)" $conf)
-  dir=$(xmllint --xpath "string(dsas/tasks/task[@id='$id']/@dir)" $conf)
-  name=$(xmllint --xpath "string(dsas/tasks/task[@id='$id']/@name)" $conf)
+  local dirlist files file
+  local id=$1
+  local uri=$(get_uri)
+  local dir=$(xmllint --xpath "string(dsas/tasks/task[$id]/directory)" $CONF)
+  local name=$(xmllint --xpath "string(dsas/tasks/task[$id]/name)" $CONF)
 
+
+  if [ -z "$uri" ]; then
+    myecho "Empty Uri for task $name"
+    return
+  fi
   # Create directory if needed
-  [ -d $haut/$dir ] || mkdir -p $haut/$dir
+  [ -d ${DSAS_HAUT}/$dir ] || mkdir -p ${DSAS_HAUT}/$dir
 
-  # Download the directory contents
-  dirlist=$(curl $uri 2> /dev/null)
-  files=$(fileargs $dirlist)
+  # Special case for scp, because it can only have one file
+  if [ "${uri:0:4}" == "scp:" ]; then
+    myecho "Downloading file: $(basename $uri)"
+    get "${uri}" "${DSAS_HAUT}/${dir}/${basename $uri}"
+  else
+    files=$(get_dirlist $uri)
 
-  if [ "$clean" == "true" ]; then
     # Remove files locally that are no longer available sur le URI
-    for localfile in $(ls -1 $haut/$dir); do
-      if [[ "$files" != *"$localfile"* ]]; then
-        echo "Removing stale file: $localfile"
-        rm $haut/$dir/$localfile
+    for file in $(ls -1 $DSAS_HAUT/$dir); do
+      # Ignore directories for now
+      [ "${file: -1}" == "/" ] && continue
+      
+      if [[ "$files" != *"$file"* ]]; then
+        myecho "Removing stale file: $file"
+        rm $DSAS_HAUT/$dir/$file
+      fi
+    done
+
+    # Download the missing files
+    for file in $files; do
+      # Ignore directories for now
+      [ "${file: -1}" == "/" ] && continue
+      if [ ! -f "$DSAS_HAUT/$dir/$file" ]; then
+        myecho "Downloading file: $file"
+        get "${uri}${file}" "${DSAS_HAUT}/${dir}/${file}"
       fi
     done
   fi
-
-  # Download the missing files
-  for file in $files; do
-    if [ ! -f "$haut/$dir/$file" ]; then
-      echo "Downloading file: $file"
-      $(umask 007 && curl -o $haut/$dir/$file $uri$file 2> /dev/null)
-    fi
-  done
-}
-
-# Usage : check_checksum <file> <chksum> <type>
-check_checksum() {
-  _file=$1
-  _chksum=$2
-  _chktype=$3
-
-  case $_chktype in
-    sha512)
-      chk=$(cat $_file | sha512sum - | sed -e "s/ -//g")
-      ;;
-    sha256)
-      chk=$(cat $_file | sha256sum - | sed -e "s/ -//g")
-      ;;
-    sha)
-      chk=$(cat $_file | sha1sum - | sed -e "s/ -$//g")
-      ;;
-    md5)
-      chk=$(cat $_file | md5sum - | sed -e "s/ -$//g")
-      ;;
-    *)
-     return 0
-     ;;
-  esac
-
-  if [ $chk != $_chksum ]; then
-    return 0
-  fi
-  return 1
 }
 
 get_packages() {
-  dest=$1
-  uri=$2
+  local file chktype chksum
+  local dest=$1
+  local uri=$2
   shift 2
   while [ "$#" -gt 2 ]; do
     if [ ${1: -3} == "rpm" ]; then
@@ -94,119 +72,142 @@ get_packages() {
      chksum=$2
     fi
     if [ -f "$dest/$file" ]; then
-      if  check_checksum $dest/$file $chksum $chktype; then
+      if check_checksum $dest/$file $chksum $chktype; then
         # Checksum of file is different redownload the file
-        echo "Downloading file $file [Checksum different!!]"
-        $(umask 007 && curl --create-dirs -o $dest/$file $uri/$file 2> /dev/null)
+        myecho "Downloading file $file [Checksum different!!]"
+        [ -d "$(dirname $dest/$file)" ] || mkdir -p $(dirname $dest/$file)
+        get $uri/$file $dest/$file
       else
-        echo "Skipping file $file"
+        myecho "Skipping file $file"
       fi
     else
-      echo "Downloading file $file"
-      $(umask 007 && curl --create-dirs -o $dest/$file $uri/$file 2> /dev/null)
+      myecho "Downloading file $file"
+      [ -d "$(dirname $dest/$file)" ] || mkdir -p $(dirname $dest/$file)
+      get $uri/$file $dest/$file
     fi
     shift 3
   done
 }
 
 getrepo() {
-  id=$1
-  uri=$2
-  check=$(xmllint --xpath "string(dsas/tasks/task[@id='$id']/check/@type)" $conf)
-  case $check in
-    deb) echo "Check DEB files is not yet implemented"; return; ;;
+  local filelist chksum chktype unzipfile filetable _file
+  local id=$1
+  local uri=$(get_uri)
+  local dir=$(xmllint --xpath "string(dsas/tasks/task[$id]/directory)" $CONF)
+  local name=$(xmllint --xpath "string(dsas/tasks/task[$id]/name)" $CONF)
+  local type=$(xmllint --xpath "string(dsas/tasks/task[$id]/type)" $CONF)
+
+  case $type in
     repomd|rpm)
-       dir=$(xmllint --xpath "string(dsas/tasks/task[@id='$id']/@dir)" $conf)
-       clean=$(xmllint --xpath "string(dsas/tasks/task[@id='$id']/@clean)" $conf)
-       name=$(xmllint --xpath "string(dsas/tasks/task[@id='$id']/@name)" $conf)
-
        # Create the destination directory if needed
-       [ -d $haut/$dir ] && mkdir -p $haut/$dir
+       [ -d "$DSAS_HAUT/$dir" ] || mkdir -p $DSAS_HAUT/$dir
 
-       echo "Downloading repodata/repomd.xml from $name"
-       $(umask 007 && curl --create-dirs -o $haut/$dir/repodata/repomd.xml \
-            $uri/repodata/repomd.xml 2> /dev/null)
-       [ "$check" == "rpm" ] || $(umask 007 && curl --create-dirs \
-            -o $haut/$dir/repodata/repomd.xml.asc \
-            $uri/repodata/repomd.xml.asc 2> /dev/null)
+       myecho "Downloading repodata/repomd.xml from $name"
+       [ -d $DSAS_HAUT/$dir/repodata ] || mkdir -p $DSAS_HAUT/$dir/repodata
+
+       get -force "$uri/repodata/repomd.xml" "$DSAS_HAUT/$dir/repodata/repomd.xml" 
+       [ "$type" == "rpm" ] || get -force "$uri/repodata/repomd.xml.asc" "$DSAS_HAUT/$dir/repodata/repomd.xml.asc" 
 
        # Identify the primary file list and download it
        # Note that we have to ignore the xml namespace (initial cat/sed)
-       filelist=$(cat $haut/$dir/repodata/repomd.xml | \
+       filelist=$(cat $DSAS_HAUT/$dir/repodata/repomd.xml | \
          sed -e "s:repomd xmlns:repomd ignore:g" | \
          xmllint --xpath 'string(//repomd/data[@type="primary"]/location/@href)' - )
-       echo "Downloading primary file list $filelist for $name"
-       $(umask 007 && curl --create-dirs -o $haut/$dir/$filelist \
-           $uri/$filelist 2> /dev/null)
+       myecho "Downloading primary file list $filelist for $name"
+       get -force "$uri/$filelist" "$DSAS_HAUT/$dir/$filelist"
 
        # Verify its checksum
-       chksum=$(cat $haut/$dir/repodata/repomd.xml | \
+       chksum=$(cat $DSAS_HAUT/$dir/repodata/repomd.xml | \
          sed -e "s:repomd xmlns:repomd ignore:g" | \
          xmllint --xpath 'string(//repomd/data[@type="primary"]/checksum)' - )
-       chktype=$(cat $haut/$dir/repodata/repomd.xml | \
+       chktype=$(cat $DSAS_HAUT/$dir/repodata/repomd.xml | \
          sed -e "s:repomd xmlns:repomd ignore:g" | \
          xmllint --xpath 'string(//repomd/data[@type="primary"]/checksum/@type)' - )
-       if  check_checksum $haut/$dir/$filelist $chksum $chktype; then
-         2>1 echo "Error verifiying checksum of $filelist"
+       if  check_checksum $DSAS_HAUT/$dir/$filelist $chksum $chktype; then
+         2>1 echo "Error verifying checksum of $filelist"
          return
        fi
 
        # Unzip and verify the checksum of primary.xml
-       chksum=$(cat $haut/$dir/repodata/repomd.xml | \
+       chksum=$(cat $DSAS_HAUT/$dir/repodata/repomd.xml | \
           sed -e "s:repomd xmlns:repomd ignore:g" | \
           xmllint --xpath 'string(//repomd/data[@type="primary"]/open-checksum)' - )
-       chktype=$(cat $haut/$dir/repodata/repomd.xml | \
+       chktype=$(cat $DSAS_HAUT/$dir/repodata/repomd.xml | \
           sed -e "s:repomd xmlns:repomd ignore:g" | \
           xmllint --xpath 'string(//repomd/data[@type="primary"]/open-checksum/@type)' - )
        unzipfile=$(echo $filelist | sed -e "s/.gz//g")
-       gunzip -k -f $haut/$dir//$filelist
-       if  check_checksum $haut/$dir/$unzipfile $chksum $chktype; then
-         2>1 echo "Error verifiying checksum of $unzipfile"
+       gunzip -k -f $DSAS_HAUT/$dir/$filelist
+       if  check_checksum $DSAS_HAUT/$dir/$unzipfile $chksum $chktype; then
+         2>1 echo "Error verifying checksum of $unzipfile"
          return
        fi
 
        # Recover a table of the hashtype, hash and file names
-       filetable=$(cat $haut/$dir/$unzipfile | \
+       filetable=$(cat $DSAS_HAUT/$dir/$unzipfile | \
           sed -e "s/xmlns=/ignore=/g" | \
           xmllint --xpath '//package[@type="rpm"]/location | //package[@type="rpm"]/checksum' - | \
           sed -e 's:.*href="\(.*\)"/>$:\1:g' \
             -e 's:.*type="\([^"]*\)"[^>]*>\([0-9a-fA-F]*\)</checksum>:\1 \2:g')
 
-       if [ "$clean" == "true" ]; then
-         # Remove the files in our tree not listed in primary.xml
-         for _file in $(cd $haut/$dir; find . -path ./repodata -prune -type f -o -type f); do
-           if [[ "$filetable" != *"${_file:2}"* ]]; then
-             echo "Removing stale file ${_file:2}"
-             rm $haut/$dir/${_file:2}
-           fi
-         done
-       fi
+       # Remove the files in our tree not listed in primary.xml
+       for _file in $(cd $DSAS_HAUT/$dir; find . -path ./repodata -prune -type f -o -type f); do
+         if [[ "$filetable" != *"${_file:2}"* ]]; then
+           myecho "Removing stale file ${_file:2}"
+           rm $DSAS_HAUT/$dir/${_file:2}
+         fi
+       done
 
        # Download the packages
-       get_packages $haut/$dir $uri $filetable
+       get_packages "$DSAS_HAUT/$dir" $uri $filetable
        ;;
     *) echo "Unrecognized repositiory check type $check"; ;;
   esac
 }
 
-[ -d /home/dsas/haut ] && haut=/home/dsas/haut
-[ -z $bas ] && [ -d /home/haut ] && haut=/home/haut
-[ -z $haut ] && $(2>1 echo "Zone haut not found"; exit 1)
+help() {
+  echo "Usage: $(basename $0)  [Options] ID [ID...]"
+  echo "Get files given by the task ID(s)"
+  echo "     -v|--verbose    Log all files verified"
+  echo "     -q|--quiet      Log only files failing to verifiy"
+  echo "     -n|--dryrun     Perform no actions"
+  echo "     -?|-h|--help    Print this help"
+}
 
-for _id in $(xmllint --xpath 'dsas/tasks/task/@id' $conf); do
-  eval $_id
-  type=$(xmllint --xpath "string(dsas/tasks/task[@id='$id']/@type)" $conf)
-  uri=$(xmllint --xpath "string(dsas/tasks/task[@id='$id']/uri)" $conf)
-  if [ "$#" -gt "0" ]; then
-    name=$(xmllint --xpath "string(dsas/tasks/task[@id='$id']/@name)" $conf)
-    [[ "$*" == *"$name"* ]] || continue
-  fi
-  if [ ! -z $uri ]; then
-    case $type in
-      linux)  getrepo $id $uri; ;;
-      directory) getdirectory $id $uri; ;;
-      *) echo "Unknown task type : $type"; ;;
-    esac
-  fi
+check_dsas
+
+# Parse options
+ids=""
+while [ "$#" -gt 0 ]; do
+  case $1 in
+    -v|--verbose) verbose=1 ;;
+    -q|--quiet) verbose=0 ;;
+    -n|--dryrun) dryrun=1 ;;
+    -?|-h|--help) help; exit 0 ;;
+    -*) 1>&2 echo "Unrecognized option : $1"; help; exit 1 ;;
+    *) ids="$ids $1" ;;
+  esac
+  shift 1
+done
+
+# If dryrun, force verbose
+[ $dryrun -ne 0 ] && verbose=1
+
+# Check that all ids are valid before doing anything
+idx=""
+for _id in $ids; do
+  task_id_to_idx $_id
+  _idx=$?
+  [ $_idx -lt 1 ] && (echo "Task id ($_id) does not exist"; exit -1)
+  idx="$idx $_idx"
+done
+
+for _idx in $idx; do
+  type=$(xmllint --xpath "string(dsas/tasks/task[$_idx]/type)" $CONF)
+  case $type in
+    rpm|repomd) getrepo $_idx; ;;
+    deb) echo "DEB files are not yet implemented"; continue; ;;
+    authenticode|openssl|gpg) getdirectory $_idx; ;;
+    *) echo "Unknown task type : $type"; ;;
+  esac
 done
 
