feat: First version of deb checking

diff --git a/append/usr/local/sbin/checkfiles b/append/usr/local/sbin/checkfiles
--- a/append/usr/local/sbin/checkfiles
+++ b/append/usr/local/sbin/checkfiles
@@ -341,7 +341,7 @@ verifdirectory() {
   fi
 
   # Create directory if needed
-  [ -d "$DSAS_BAS/$dir" ] || $(umask 007 && mkdir -p "$DSAS_BAS/$dir" && chgrp -R $grp "$DSAS_BAS/$(echo $dir | cut -d/ -f1)")
+  [ -d "$DSAS_BAS/$dir" ] || $(umask 007; mkdir -p "$DSAS_BAS/$dir"; chgrp -R $grp "$DSAS_BAS/$(echo $dir | cut -d/ -f1)")
 
   # Remove the files in our tree bas and not in haut.
   filetable=$(cd "$DSAS_HAUT/$dir"; find . -type f)
@@ -464,7 +464,7 @@ verifrepo() {
   fi 
 
   # Create the destination directory if needed
-  [ -d "$DSAS_BAS/$dir" ] || $(umask 007 && mkdir -p "$DSAS_BAS/$dir" && chgrp $grp -R "$DSAS_BAS/$(echo $dir | cut -d/ -f1)")
+  [ -d "$DSAS_BAS/$dir" ] || $(umask 007; mkdir -p "$DSAS_BAS/$dir"; chgrp $grp -R "$DSAS_BAS/$(echo $dir | cut -d/ -f1)")
 
   # Copy repomd.xml* to $bas
   ln "$DSAS_HAUT/$dir/repodata/repomd.xml" "$DSAS_BAS/$dir/repodata/repomd.xml"
@@ -533,13 +533,143 @@ verifrepo() {
   /bin/rm -fr "$tempdir"
 }
 
+
+verifdeb(){
+  local chktyp inhash hashtyp _hash _hash_md5 _hash_sha256 _size _file 
+  local j pool have_pool packages inpackage tempdir
+  local id=$1
+  local dir=$(xmllint --xpath "string(dsas/tasks/task[$id]/directory)" $CONF)
+  local name=$(xmllint --xpath "string(dsas/tasks/task[$id]/name)" $CONF)
+  local type=$(xmllint --xpath "string(dsas/tasks/task[$id]/type)" $CONF)
+
+  pool=$(dirname "$dir")
+  have_pool="0"
+  while [ -n "$pool" ]; do
+    [ -d "$DSAS_HAUT/$pool/pool" ] && have_pool="1" && break
+    pool=$(dirname "$pool")
+  done
+  [ "$have_pool" == "0" ] && $(1>&2 echo "Debian pool directory not found"; exit 1)
+
+  tempdir=$(mktemp -d)
+  j=1
+  while :; do
+    fprint=$(xmllint --xpath "string(dsas/tasks/task[$id]/cert[$j]/fingerprint)" "$CONF")
+    [ -z "$fprint" ] && break;
+    idx=$(get_certificate $fprint)
+    [ -z "$idx" ] && { 1>&2 echo "Certificate used by task($id) not found !!"; cleanup_and_exit 1 "$tempdir"; }
+    cat /tmp/cert.$$ >> $tempdir/cert.0
+    j=$((j + 1))
+  done
+  gpg --dearmor "$tempdir/cert.0"
+
+  if ! gpg --no-default-keyring --keyring "$tempdir/cert.0.gpg"  \
+        --verify "$DSAS_HAUT/$dir/Release.gpg" \
+        "$DSAS_HAUT/$dir/Release" >& /dev/null; then
+    1>&2 echo "Failed to verify Release signature"
+    cleanup_and_exit 1 "$tempdir"
+  fi
+  if ! gpg --no-default-keyring --keyring "$tempdir/cert.0.gpg"  \
+        --verify "$DSAS_HAUT/$dir/InRelease" >& /dev/null; then
+    1>&2 echo "Failed to verify InRelease signature"
+    cleanup_and_exit 1 "$tempdir"
+  fi
+
+  # Create the destination directory if needed
+  [ -d "$DSAS_BAS/$dir" ] || $(umask 007; mkdir -p $DSAS_BAS/$dir; chgrp $grp -R $DSAS_BAS/$dir)
+
+  # Copy *Release* to $bas
+  for _file in "Release Release.gpg InRelease"; do
+    [ -f "$DSAS_HAUT/$dir/$_file" ] && ln "$DSAS_HAUT/$dir/$_file" "$DSAS_BAS/$dir/$_file"
+  done
+
+  # Identify if the Release file has SHA256 et/ou MD5 hashes
+  grep -qx "MD5Sum:" "$DSAS_HAUT/$dir/Release" && hashtyp="MD5Sum:" && chktyp="md5"
+  grep -qx "SHA1:" "$DSAS_HAUT/$dir/Release" && hashtyp="SHA1:" && chktyp="sha"
+  grep -qx "SHA256:" "$DSAS_HAUT/$dir/Release" && hashtyp="SHA256:" && chktyp="sha256"
+
+  # Identify all files listed in Release and download them
+  inhash=0
+  while read -r line; do
+    # Assume that each hash is listed after the correct flag and has
+    # a leading space
+    [ "$inhash" == "0" ] && [[ "$line" =~ "^$hashtyp$" ]] && inhash="1" && continue
+    [ "$inhash" == "1" ] && [[ "$line" =~ ":$" ]] && inhash="0" && continue
+    [ "$inhash" == "0" ] && continue
+
+    IFS=' ' read _hash _size _file << EOF
+$line
+EOF
+    if [ -f "$DSAS_HAUT/$dir/$_file" ]; then
+      # If file exists in bas skip. Hardlinked, so test is fast
+      [ "$DSAS_HAUT/$dir/$_file" -ef "$DSAS_BAS/$dir/$_file" ] && continue
+
+      if  check_checksum "$DSAS_HAUT/$dir/$_file" $_hash $chktyp; then
+        msgline "$DSAS_HAUT/$dir/$_file" 1  
+      else
+        msgline "$DSAS_HAUT/$dir/$_file" 0
+        [ -d "$(dirname "$DSAS_BAS/$dir/$_file")" ] || $(umask 007; mkdir -p "$(dirname "$DSAS_BAS/$dir/$_file")"; chgrp $grp -R "$(dirname "$DSAS_BAS/$dir/$_file")")
+        ln "$DSAS_HAUT/$dir/$_file" "$DSAS_BAS/$dir/$_file"
+      fi
+      # For now ignore missing files
+    fi
+  done < $DSAS_HAUT/$dir/Release
+
+  # For each file Packages.gz check the listed files into the pool directory
+  for packages in $(find "$DSAS_BAS/$dir" -name "Packages.gz"); do
+    inpackage=0
+    _file=""
+    _hash_md5=""
+    _hash_sha256=""
+    zcat "$packages" | while read -r line; do
+      # Use sed rather than xargs to strip leading/trailing whitespace as strings might
+      # contain quotes and other special characters
+      [[ "$line" =~ "Filename:" ]] && _file="$(echo $line | cut -d: -f2- | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')" && continue
+      [[ "$line" =~ "MD5sum:" ]] && _hash_md5="$(echo $line | cut -d: -f2- | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')" && continue
+      [[ "$line" =~ "SHA256:" ]] && _hash_sha256="$(echo $line | cut -d: -f2- | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')" && continue
+      if [ -z "$(echo $line | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')" ]; then
+        if [ -f "$DSAS_HAUT/$pool/$_file" ]; then
+          # If file exists in bas skip. Hardlinked, so test is fast
+          [ "$DSAS_HAUT/$pool/$_file" -ef "$DSAS_BAS/$pool/$_file" ] && continue
+
+          if [ -n "$hash_sha256"  ] && check_checksum "$DSAS_HUAT/$pool_local/$_file" $_hash_dha256 sha256; then
+            msgline "$DSAS_HAUT/$pool/$_file" 1
+          elif [ -n "$hash_md5" ] && check_checksum "$DSAS_HUAT/$pool/$_file" $_hash_md5 md5; then
+            msgline "$DSAS_HAUT/$pool/$_file" 1
+          else
+            msgline "$DSAS_HAUT/$pool/$_file" 0 
+            [ -d "$(dirname i"$DSAS_BAS/$pool/$_file")" ] || $(umask 007; mkdir -p "$(dirname "$DSAS_BAS/$pool/$_file")"; chgrp $grp -R "$(dirname "$DSAS_BAS/$pool/$_file")")
+            ln "$DSAS_HAUT/$pool/$_file" "$DSAS_BAS/$pool/$_file"          
+          fi
+        fi
+        _file=""
+        _hash_md5=""
+        _hash_sha256=""
+      fi
+    done
+  done
+
+  exit 0
+}
+
 passdirectory(){
-  local filetable file status i j fprint tempdir idx auth
+  local filetable file status i j fprint tempdir idx auth pool have_pool
   local id=$1
   local dir=$(xmllint --xpath "string(dsas/tasks/task[$id]/directory)" "$CONF")
 
-  # Create directory if needed
-  [ -d "$DSAS_BAS/$dir" ] ||  $(umask 007 && mkdir -p "$DSAS_BAS/$dir" && chgrp $grp -R "$DSAS_BAS/$(echo $dir | cut -d/ -f1)")
+  if [ "$2" == "deb" ]; then
+    pool=$(dirname "$dir")
+    have_pool="0"
+    while [ -n "$pool" ]; do
+      [ -d "$DSAS_HAUT/$pool/pool" ] && have_pool="1" && break
+      pool=$(dirname "$pool")
+    done
+    [ "$have_pool" == "0" ] && $(1>&2 echo "Debian pool directory not found"; exit 1)
+  fi
+
+  # Create directories if needed
+  for _d in $(cd "$DSAS_HAUT"; find "$dir" -type d); do
+    [ -d "$DSAS_BAS/$_d" ] || $(umask 007; mkdir -p "$DSAS_BAS/$_d"; chgrp $grp -R "$DSAS_BAS/$_d")
+  done
 
   # Remove the files in our tree bas and not in haut.
   filetable=$(cd "$DSAS_HAUT/$dir"; find . -type f)
@@ -558,6 +688,31 @@ passdirectory(){
     # the logs aren't yet used
     ln "$DSAS_HAUT/$file" "$DSAS_BAS/$file"
   done
+
+  if [ "$2" == "deb" ]; then
+    # Create directories if needed
+    for _d in $(cd "$DSAS_HAUT"; find "$pool/pool" -type d); do
+      [ -d "$DSAS_BAS/$_d" ] || $(umask 007; mkdir -p "$DSAS_BAS/$_d"; chgrp $grp -R "$DSAS_BAS/$_d")
+    done
+
+    # Remove the files in our tree bas and not in haut.
+    filetable=$(cd "$DSAS_HAUT/$pool/pool"; find . -type f)
+    for file in $(cd "$DSAS_BAS/$pool/pool"; find . -type f); do
+      if [[ "$filetable" != *"${file:2}"* ]]; then
+        myecho "Removing stale file ${file:2}"
+        rm -f "$DSAS_BAS/$pool/pool/${file:2}"
+      fi
+    done
+
+    for file in $(cd "$DSAS_HAUT"; find "$pool/pool" -type f); do
+      # If file exists in bas skip. Hardlinked, so test is fast
+      [ "$DSAS_HAUT/$file" -ef "$DSAS_BAS/$file" ] && continue
+
+      # Don't log the transfers with msgline for the machine haut as
+      # the logs aren't yet used
+      ln "$DSAS_HAUT/$file" "$DSAS_BAS/$file"
+    done
+  fi
 }
 
 check_dsas
@@ -596,14 +751,14 @@ for _id in $ids; do
 done
 
 for _id in $idx; do
+  type=$(xmllint --xpath "string(dsas/tasks/task[$_id]/type)" "$CONF")
   if [ "$TYP" == "haut" ]; then
     # No verification on the machine haut
-    passdirectory $_id
+    passdirectory $_id $type
   else
-    type=$(xmllint --xpath "string(dsas/tasks/task[$_id]/type)" "$CONF")
     case $type in
       rpm|repomd) verifrepo $_id; ;;
-      deb) 1>&2 echo "DEB files are  are not yet implemented"; exit 1; ;;
+      deb) verifdeb $_id; ;;
       authenticode|openssl|gpg|liveupdate|cyberwatch) verifdirectory $_id; ;; 
       *) 1>&2 echo "Unknown task type : $type"; exit 1 ;;
     esac
diff --git a/append/usr/local/sbin/getfiles b/append/usr/local/sbin/getfiles
--- a/append/usr/local/sbin/getfiles
+++ b/append/usr/local/sbin/getfiles
@@ -48,7 +48,7 @@ getdirectory() {
   isdir=""
   [ "${uri: -1}" == "/" ] && isdir="1"
   [ "${uri: -1}" == "\\" ] && isdir="1"
-  [ -z "$isdir" ] && $(lftp -c "open '$uri'") && isdir="1"
+  [ -z "$isdir" ] && $(lftp -c "$opt open '$uri'") && isdir="1"
 
   if [ -z "$isdir" ]; then
     myecho "Downloading file : $(basename "$uri")"
@@ -191,6 +191,121 @@ getrepo() {
   exit 0
 }
 
+getdeb() {
+  local chktyp inhash hashtyp _hash _hash_md5 _hash_sha256 _size _file
+  local pool pool_local have_pool packages inpackage
+  local id=$1
+  local uri=$(get_uri $id)
+  local dir=$(xmllint --xpath "string(dsas/tasks/task[$id]/directory)" $CONF)
+  local name=$(xmllint --xpath "string(dsas/tasks/task[$id]/name)" $CONF)
+  local type=$(xmllint --xpath "string(dsas/tasks/task[$id]/type)" $CONF)
+
+  case $type in
+    deb)
+       # Find the pool directory
+       pool=$(dirname "$uri")
+       pool_local=$(dirname "$dir")
+       have_pool="0"
+       while [ -n "$pool" ]; do
+         $(lftp -c "$opt open '$pool/pool'" >& /dev/null) && have_pool="1" && break
+         pool=$(dirname "$pool")
+         pool_local=$(dirname "$pool_local")
+       done
+       [ "$have_pool" == "0" ] && $(1>&2 echo "Debian pool directory not found"; exit 1)
+
+       # Create the destination directory if needed
+       [ -d "$DSAS_HAUT/$dir" ] || $(umask 007 && mkdir -p $DSAS_HAUT/$dir)
+
+       myecho "Downloading Release/Release.gpg from $name"
+       if [ "$verbose" -eq 0 ]; then
+         lftp -c "$opt get -e '$uri/Release' -o '$DSAS_HAUT/$dir/Release'" >& /dev/null
+         lftp -c "$opt get -e '$uri/Release.gpg' -o '$DSAS_HAUT/$dir/Release.gpg'" >& /dev/null
+         lftp -c "$opt get -e '$uri/InRelease' -o '$DSAS_HAUT/$dir/InRelease'" >& /dev/null
+       else
+         lftp -c "$opt get -e '$uri/Release' -o '$DSAS_HAUT/$dir/Release'"
+         lftp -c "$opt get -e '$uri/Release.gpg' -o '$DSAS_HAUT/$dir/Release.gpg'"
+         lftp -c "$opt get -e '$uri/InRelease' -o '$DSAS_HAUT/$dir/InRelease'"
+       fi
+
+       # Identify if the Release file has SHA256 et/ou MD5 hashes
+       grep -qx "MD5Sum:" "$DSAS_HAUT/$dir/Release" && hashtyp="MD5Sum:" && chktyp="md5"
+       grep -qx "SHA1:" "$DSAS_HAUT/$dir/Release" && hashtyp="SHA1:" && chktyp="sha"
+       grep -qx "SHA256:" "$DSAS_HAUT/$dir/Release" && hashtyp="SHA256:" && chktyp="sha256"
+
+       # Identify all files listed in Release and download them
+       inhash=0
+       while read -r line; do
+         # Assume that each hash is listed after the correct flag and has
+         # a leading space
+         [ "$inhash" == "0" ] && [[ "$line" =~ "^$hashtyp$" ]] && inhash="1" && continue
+         [ "$inhash" == "1" ] && [[ "$line" =~ ":$" ]] && inhash="0" && continue
+         [ "$inhash" == "0" ] && continue
+
+         IFS=' ' read _hash _size _file << EOF
+$line
+EOF
+         if [ -f "$DSAS_HAUT/$dir/$_file" ]; then
+           if check_checksum "$DSAS_HAUT/$dir/$_file" $_hash $chktyp; then
+             myecho "Downloading file $_file [Checksum different!!]"
+             [ "$verbose" -eq 0 ] && lftp -c "$opt get -e '$uri/$_file' -o '$DSAS_HAUT/$dir/$_file'" >& /dev/null
+             [ "$verbose" -eq 0 ] || lftp -c "$opt get -e '$uri/$_file' -o '$DSAS_HAUT/$dir/$_file'"
+           else
+             myecho "Skipping file $_file"
+           fi
+         else
+           myecho "Downloading file $_file"
+           [ -d "$(dirname "$DSAS_HAUT/$dir/$_file")" ] || $(umask 007; mkdir -p "$(dirname "$DSAS_HAUT/$dir/$_file")")
+           [ "$verbose" -eq 0 ] && lftp -c "$opt get -e '$uri/$_file' -o '$DSAS_HAUT/$dir/$_file'" >& /dev/null
+           [ "$verbose" -eq 0 ] || lftp -c "$opt get -e '$uri/$_file' -o '$DSAS_HAUT/$dir/$_file'"
+         fi
+       done < $DSAS_HAUT/$dir/Release
+
+       # For each file Packages.gz download the listed files into the pool directory
+       for packages in $(find "$DSAS_HAUT/$dir" -name "Packages.gz"); do
+         inpackage=0
+         _file=""
+         _hash_md5=""
+         _hash_sha256=""
+         zcat "$packages" | while read -r line; do
+           # Use sed to strip leading and trailing space, as can't used xargs due to possible
+           # illegal characters like single quotes in strings. 
+           [[ "$line" =~ "Filename:" ]] && _file="$(echo $line | cut -d: -f2- | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')" && continue
+           [[ "$line" =~ "MD5sum:" ]] && _hash_md5="$(echo $line | cut -d: -f2- | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')" && continue
+           [[ "$line" =~ "SHA256:" ]] && _hash_sha256="$(echo $line | cut -d: -f2- | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')" && continue
+           if [ -z "$(echo $line | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')" ]; then
+             if [ -f "$DSAS_HAUT/$pool_local/$_file" ]; then
+               [ -n "$hash_md5" ] && check_checksum "$DSAS_HUAT/$pool_local/$_file" $_hash_md5 md5
+               [ "$?" -eq 0 ] && [ -n "$hash_sha256"  ] && check_checksum "$DSAS_HUAT/$pool_local/$_file" $_hash_sha256 sha256
+               
+               if [ "$?" -eq 0 ]; then
+                 myecho "Downloading file $_file [Checksum different!!]"
+                 [ "$verbose" -eq 0 ] && lftp -c "$opt get -e '$pool/$_file' -o '$DSAS_HAUT/$pool_local/$_file'" >& /dev/null
+                 [ "$verbose" -eq 0 ] || lftp -c "$opt get -e '$pool/$_file' -o '$DSAS_HAUT/$pool_local/$_file'"
+               else
+                 myecho "Skipping file $_file"
+               fi
+             elif [ -n "$_file" ]; then
+               myecho "Downloading file $_file"
+               [ -d "$(dirname "$DSAS_HAUT/$pool_local/$_file")" ] || $(umask 007 && mkdir -p "$(dirname "$DSAS_HAUT/$pool_local/$_file")")
+               [ "$verbose" -eq 0 ] && lftp -c "$opt get -e '$pool/$_file' -o '$DSAS_HAUT/$pool_local/$_file'" >& /dev/null
+               [ "$verbose" -eq 0 ] || lftp -c "$opt get -e '$pool/$_file' -o '$DSAS_HAUT/$pool_local/$_file'"
+             fi
+             _file=""
+             _hash_md5=""
+             _hash_sha256=""
+           fi
+         done
+       done
+
+       ;;
+
+     *) 1>&2 echo "Unknown file checking type"; exit 1; ;;
+  esac
+
+  exit 0
+}
+
+
 help() {
   echo "Usage: $(basename $0)  [Options] ID"
   echo "Get files given by the task ID"
@@ -234,7 +349,7 @@ for _idx in $idx; do
   type=$(xmllint --xpath "string(dsas/tasks/task[$_idx]/type)" $CONF)
   case $type in
     rpm|repomd) getrepo $_idx; ;;
-    deb) 1>&2 echo "DEB files are not yet implemented"; exit 1; ;;
+    deb) getdeb $_idx; ;;
     authenticode|openssl|gpg|liveupdate|cyberwatch) getdirectory $_idx; ;;
     *) 1>&2 echo "Unknown task type : $type"; exit 1; ;;
   esac
