fix: lots of fixes after static analysis with shellchecker

diff --git a/append/usr/local/sbin/dsasbackup b/append/usr/local/sbin/dsasbackup
--- a/append/usr/local/sbin/dsasbackup
+++ b/append/usr/local/sbin/dsasbackup
@@ -1,16 +1,22 @@
 #! /bin/sh
+# Busybox ash not supported. Use posix SH and disable a couple of
+# ash extensions I use
+#
+# shellcheck shell=sh
+# shellcheck disable=SC2039
 
 # If root rerun as user tc
-if [ $(id -u) == 0 ];then
-  sudo -E -u tc $0 $*
+if [ "$(id -u)" = 0 ];then
+  sudo -E -u tc "$0" "$@"
   exit $?
 fi
 
 # if not user tc, quit
 [ "$(whoami)" != "tc" ] && { 1>&2 echo "$0: Must de run as user 'tc'"; exit 1; }
 
-if [ -f "$(dirname $0)/dsas_common.sh" ]; then
-  . $(dirname $0)/dsas_common.sh
+if [ -f "$(dirname "$0")/dsas_common.sh" ]; then
+  # shellcheck source=append/usr/local/sbin/dsas_common.sh
+  . "$(dirname "$0")/dsas_common.sh"
 else
   1>&2 echo "Common functions not found !!"
   exit 1
@@ -40,7 +46,7 @@ RESTORE=0
 APPLY=0
 BKP=""
 PASSWD=""
-OPTS=""
+
 while [ "$#" -gt 0 ]; do
   case $1 in
     -r|--restore) RESTORE=1 ;;
@@ -57,44 +63,47 @@ done
 [ -z "$BKP" ] && BKP="/tmp/dsas_backup.tgz"
 
 blowfish_encrypt(){
-  cat << EOD | /usr/bin/bcrypt -c $1 2> /dev/null  
+  cat << EOD | /usr/bin/bcrypt -c "$1" 2> /dev/null  
 $2
 $2
 EOD
 }
 
 blowfish_decrypt(){
-  cat << EOD | /usr/bin/bcrypt -o $1.bfe 2> /dev/null > $1
+  cat << EOD | /usr/bin/bcrypt -o "$1.bfe" 2> /dev/null > "$1"
 $2
 EOD
 }
 
 if [ "$RESTORE" -eq 0 ]; then
   # Create the backup on the machine haut
-  (umask 077; sudo sudo -u haut ssh tc@$INTERCO_HAUT sudo tar -C / -c -z -f - $FILES > /tmp/haut.tgz)
-  [ -n "$PASSWD" ] && (umask 077; cd /tmp; blowfish_encrypt haut.tgz $PASSWD)
+  # shellcheck disable=SC2024
+  # shellcheck disable=SC2086
+  (umask 077; sudo sudo -u haut ssh "tc@$INTERCO_HAUT" sudo tar -C / -c -z -f - $FILES > /tmp/haut.tgz)
+  [ -n "$PASSWD" ] && (umask 077; cd /tmp || exit 1; blowfish_encrypt haut.tgz "$PASSWD")
   
   # Get the backup for the machine bas
+  # shellcheck disable=SC2024
+  # shellcheck disable=SC2086
   (umask 077; sudo tar -C / -c -z -f - $FILES > /tmp/bas.tgz)
-  [ -n "$PASSWD" ] && (umask 077; cd /tmp; blowfish_encrypt bas.tgz $PASSWD)
+  [ -n "$PASSWD" ] && (umask 077; cd /tmp || exit 1; blowfish_encrypt bas.tgz "$PASSWD")
 
   # Create the backup file
   [ -f "$BKP" ] && /bin/rm -f $BKP  
   if [ -z "$PASSWD" ]; then
-    (umask 077; cd /tmp; tar -czf $BKP haut.tgz bas.tgz)
+    (umask 077; cd /tmp || exit 1; tar -czf $BKP haut.tgz bas.tgz)
   else
-    (umask 077; cd /tmp; tar -czf $BKP haut.tgz.bfe bas.tgz.bfe)
+    (umask 077; cd /tmp || exit 1; tar -czf $BKP haut.tgz.bfe bas.tgz.bfe)
   fi
 
   # Remove temporary files
-  (cd /tmp; /bin/rm -f haut.tgz bas.tgz haut.tgz.bfe bas.tgz.bfe)
+  (cd /tmp || exit 1; /bin/rm -f haut.tgz bas.tgz haut.tgz.bfe bas.tgz.bfe)
 else
   # Remove existing files
-  (cd /tmp; /bin/rm -f haut.tgz bas.tgz haut.tgz.bfe bas.tgz.bfe)
+  (cd /tmp || exit 1; /bin/rm -f haut.tgz bas.tgz haut.tgz.bfe bas.tgz.bfe)
 
   # Unpack the tar file
-  (umask 077; cd /tmp; tar -zxf $BKP)
-  [ $? -eq 0 ] || exit 1;
+  (umask 077; cd /tmp || exit 1; tar -zxf $BKP) || exit 1
 
   if [ -z "$PASSWD" ]; then
     [ -f "/tmp/haut.tgz" ] || { 1>&2 echo "Backup corrupted or encrypted"; exit 1; }
@@ -104,20 +113,20 @@ else
     [ -f "/tmp/bas.tgz.bfe" ] || { 1>&2 echo "Backup corrupted or not encrypted"; exit 1; }
 
     # Decrypt the files 
-    (umask 077; cd /tmp; blowfish_decrypt haut.tgz $PASSWD)
-    [ $? -eq 0 ] || { 1>&2 echo "Can not decrypt the backup. Check the password"; exit 1; }
-    (umask 077; cd /tmp; blowfish_decrypt bas.tgz $PASSWD)
-    [ $? -eq 0 ] || { 1>&2 echo "The backup is corrupted"; exit 1; }
+    (umask 077; cd /tmp || exit 1; blowfish_decrypt haut.tgz "$PASSWD") || \
+        { 1>&2 echo "Can not decrypt the backup. Check the password"; exit 1; }
+    (umask 077; cd /tmp || exit 1; blowfish_decrypt bas.tgz "$PASSWD") || \
+        { 1>&2 echo "The backup is corrupted"; exit 1; }
   fi
 
   # Control the contents of the tar files and only allow files in the list $FILES
   for bkp in /tmp/bas.tgz /tmp/haut.tgz; do
     for file in $(tar tzf $bkp); do
       for p in $FILES; do
-        if [ "${p%/}" == "$p" ]; then
-          [ "$file" == "$p" ] && continue 2  # legal file
+        if [ "${p%/}" = "$p" ]; then
+          [ "$file" = "$p" ] && continue 2  # legal file
         else
-          [ "${file:0:${#p}}" == "$p" ] && continue 2  # legal directory
+          [ "${file:0:${#p}}" = "$p" ] && continue 2  # legal directory
         fi
       done
       { 1>&2 echo "The backup contains illegal files"; exit 1; }
@@ -125,11 +134,11 @@ else
   done
 
   # The value of dsas->config->users->first should be preserved 
-  first=$(xmllint --xpath 'string(dsas/config/users/first)' $VAR/dsas_conf.xml)
+  first=$(xmllint --xpath 'string(dsas/config/users/first)' "$VAR/dsas_conf.xml")
 
   # Unpack the files on machine haut
-  cat /tmp/haut.tgz | (sudo sudo -u haut ssh tc@$INTERCO_HAUT sudo tar -C / -x -z -f -)
-  [ $? -eq 0 ] || { 1>&2 echo "Can not transfer the backup to the machine haut"; exit 1; }
+  (sudo sudo -u haut ssh "tc@$INTERCO_HAUT" sudo tar -C / -x -z -f -) < /tmp/haut.tgz || \
+      { 1>&2 echo "Can not transfer the backup to the machine haut"; exit 1; }
 
   # Unpack the files on machine bas
   (sudo tar -C / -x -z -f /tmp/bas.tgz)
@@ -141,55 +150,54 @@ else
   else
     args="$args <first>$first</first>"
   fi
-  for arg in $(xmllint --xpath "dsas/config/users/*" $VAR/dsas_conf.xml); do
+  for arg in $(xmllint --xpath "dsas/config/users/*" "$VAR/dsas_conf.xml"); do
     [[ "$arg" =~ "^<first" ]] && continue
     args="$args$arg"
   done
   args="$args\nsave"
-  echo -e "$arg" | xmllint --shell $VAR/dsas_conf.xml > /dev/null 2>&1
+  echo -e "$arg" | xmllint --shell "$VAR/dsas_conf.xml" > /dev/null 2>&1
 
   # The installed users need to be updated with adduser/deluser to correspond to
   # the users in the xml config file, but only on the machine bas
   while read -r line; do
-    user=$(echo $line | cut -d: -f1)
-    uid=$(echo $line | cut -d: -f3)
-    [ $uid -lt 1000 ] && continue
-    [ "$user" == "tc" ] && continue
-    [ "$user" == "bas" ] && continue
-    [ "$user" == "haut" ] && continue
-    [ "$user" == "verif" ] && continue
-    [ "$user" == "nobody" ] && continue
+    user=$(echo "$line" | cut -d: -f1)
+    uid=$(echo "$line" | cut -d: -f3)
+    [ "$uid" -lt 1000 ] && continue
+    [ "$user" = "tc" ] && continue
+    [ "$user" = "bas" ] && continue
+    [ "$user" = "haut" ] && continue
+    [ "$user" = "verif" ] && continue
+    [ "$user" = "nobody" ] && continue
     # Have an added user
     id=1
     while :; do
-      _user=$(xmllint --xpath "string(dsas/config/users/user[$id]/username)" $VAR/dsas_conf.xml)
+      _user=$(xmllint --xpath "string(dsas/config/users/user[$id]/username)" "$VAR/dsas_conf.xml")
       [ -z "$_user" ] && break
-      [ "$user" == "$_user" ] && continue 2
-      id=$(($id + 1))
+      [ "$user" = "$_user" ] && continue 2
+      id=$((id + 1))
     done
-    sudo deluser $user
+    sudo deluser "$user"
   done < /etc/passwd
   id=1
   while :; do
-    _user=$(xmllint --xpath "string(dsas/config/users/user[$id]/username)" $VAR/dsas_conf.xml)
+    _user=$(xmllint --xpath "string(dsas/config/users/user[$id]/username)" "$VAR/dsas_conf.xml")
     [ -z "$_user" ] && break
-    if ! cut -f1 -d: /etc/passwd | grep -x -q $_user; then
-      sudo adduser -G users -h $DSAS_HOME/$_user -s /bin/sh -D $_user
+    if ! cut -f1 -d: /etc/passwd | grep -x -q "$_user"; then
+      sudo adduser -G users -h "$DSAS_HOME/$_user" -s /bin/sh -D "$_user"
     fi
-    id=$(($id + 1))
+    id=$((id + 1))
   done
 
   # Save the restored files to the active configuration.   
-  /usr/bin/filetool.sh -b 2>&1 > /dev/null
-  [ $? -eq 0 ] || { 1>&2 echo "Error running filetool"; exit 1; }
+  /usr/bin/filetool.sh -b > /dev/null 2>&1 || { 1>&2 echo "Error running filetool"; exit 1; }
 
   # Apply the configuration if requested
   if [ "$APPLY" -ne 0 ]; then
-    sudo /etc/init.d/services/dsas apply 2>&1 > /dev/null
-    [ $? -eq 0 ] || { 1>&2 echo "Error applying the configuration"; exit 1; }
+    sudo /etc/init.d/services/dsas apply > /dev/null 2>&1 || \
+        { 1>&2 echo "Error applying the configuration"; exit 1; }
   fi
 
   # Remove temporary files
-  (cd /tmp; /bin/rm -f haut.tgz bas.tgz haut.tgz.bfe bas.tgz.bfe)
+  (cd /tmp || exit 1; /bin/rm -f haut.tgz bas.tgz haut.tgz.bfe bas.tgz.bfe)
 fi
 
diff --git a/append/usr/local/sbin/sysloghaut b/append/usr/local/sbin/sysloghaut
--- a/append/usr/local/sbin/sysloghaut
+++ b/append/usr/local/sbin/sysloghaut
@@ -1,10 +1,16 @@
 #!/bin/sh
+# Busybox ash not supported. Use posix SH and disable a couple of
+# ash extensions I use
+#
+# shellcheck shell=sh
+# shellcheck disable=SC2039
 
-if [ -f "$(dirname $0)/dsas_common.sh" ]; then
-  . $(dirname $0)/dsas_common.sh
+if [ -f "$(dirname "$0")/dsas_common.sh" ]; then
+  # shellcheck source=append/usr/local/sbin/dsas_common.sh
+  . "$(dirname "$0")/dsas_common.sh"
 else
   1>&2 echo "Common functions not found !!"
-  exit -1
+  exit 1
 fi
 
 HLOG="/var/log/messages"
@@ -14,32 +20,34 @@ HLOG0="/var/log/messages.0"
 if [ "$(whoami)" != "haut" ]; then
   [ "$#" -ne 0 ] && { 1>&2 echo "$0: No arguments permitted"; exit 1; }
   # Get the status of the last run
+  # shellcheck disable=SC2153
   LAST=$LOG/syslog.haut
   HLOGSZ=0
   HLOGH=""
   HLOGSZ0=0
   HLOGH0=""
   if [ -f "$LAST" ]; then
-    HLOGSZ=$(head -1 $LAST | cut -d' ' -f2)
+    HLOGSZ=$(head -1 "$LAST" | cut -d' ' -f2)
     [ -z "$HLOGSZ" ] && HLOGSZ=0
-    HLOGH=$(head -1 $LAST | cut -d' ' -f3)
+    HLOGH=$(head -1 "$LAST" | cut -d' ' -f3)
     [ -z "$HLOGH" ] && HLOGH=""
-    HLOGSZ0=$(grep $HLOG0 $LAST | cut -d' ' -f2)
+    HLOGSZ0=$(grep "$HLOG0" "$LAST" | cut -d' ' -f2)
     [ -z "$HLOGSZ0" ] && HLOGSZ0=0
-    HLOGH0=$(grep $HLOG0 $LAST | cut -d' ' -f3)
+    HLOGH0=$(grep "$HLOG0" "$LAST" | cut -d' ' -f3)
     [ -z "$HLOGH0" ] && HLOGH0=""
   fi
-  if [ $(id -u) == 0 ]; then
-    sudo -E -u haut $0 $HLOGSZ $HLOGSZ0 $HLOGH $HLOGH0 > $LAST.new
-  elif [ "$(whoami)" == "tc" ]; then
-    sudo sudo -E -u haut $0 $HLOGSZ $HLOGSZ0 $HLOGH $HLOGH0 > $LAST.new
+  # shellcheck disable=SC2024
+  if [ "$(id -u)" = 0 ]; then
+    sudo -E -u haut "$0" "$HLOGSZ" "$HLOGSZ0" "$HLOGH" "$HLOGH0" > "$LAST.new"
+  elif [ "$(whoami)" = "tc" ]; then
+    sudo sudo -E -u haut "$0" $HLOGSZ $HLOGSZ0 "$HLOGH" "$HLOGH0" > "$LAST.new"
   else
     1>&2 echo "$0: Must be run as user 'haut'"
     false
   fi
   status=$?
-  [ "$status" == "0" ] && mv $LAST.new $LAST
-  [ "$status" == "0" ] || rm $LAST.new 
+  [ "$status" = "0" ] && mv "$LAST.new" "$LAST"
+  [ "$status" = "0" ] || rm "$LAST.new" 
   exit $status
 fi
 
@@ -48,22 +56,22 @@ HLOGSZ=$1
 HLOGSZ0=$2
 [ "$HLOGSZ0" != "0" ] && HLOGH0=$4
 
-syslog=$(xmllint --xpath "string(dsas/config/syslog/active)" $VAR/dsas_conf.xml)
-server=$(xmllint --xpath "string(dsas/config/syslog/server)" $VAR/dsas_conf.xml)
+syslog=$(xmllint --xpath "string(dsas/config/syslog/active)" "$VAR/dsas_conf.xml")
+server=$(xmllint --xpath "string(dsas/config/syslog/server)" "$VAR/dsas_conf.xml")
 [ "$syslog" != "true" ] && exit 0 
 [ -z "$server" ] && exit 0 
 
 # Get /var/log/messages from the machine haut
 tempdir=$(mktemp -d)
-scp tc@$INTERCO_HAUT:$HLOG $tempdir/$(basename $HLOG)
+scp "tc@$INTERCO_HAUT:$HLOG" "$tempdir/$(basename "$HLOG")"
 
 parse_pri(){
   # Recovers the syslog PRI field from the linux syslog and appends the
   # RFC3164 conforming PRI field to the syslog message. The HEADER and
   # BODY of RFC3164 are left as is
-  pri=$(echo $* | cut -d' ' -f5)
-  fac=$(echo $pri | cut -d. -f1)
-  sev=$(echo $pri | cut -d. -f2)
+  pri=$(echo "$@" | cut -d' ' -f5)
+  fac=$(echo "$pri" | cut -d. -f1)
+  sev=$(echo "$pri" | cut -d. -f2)
   case $fac in
     "kern") ret=0 ;;
     "user") ret=1 ;;
@@ -83,52 +91,52 @@ parse_pri(){
     "solaris-cron") ret=15 ;;
     *) ret=16 ;;
   esac
-  ret=$(($ret * 8))
+  ret=$((ret * 8))
   case $sev in
     "emerg"|"panic") : ;;
-    "alert") ret=$(($ret + 1)) ;;
-    "crit") ret=$(($ret + 2))  ;;
-    "err"|"error") ret=$(($ret + 3))  ;;
-    "warn"|"warning") ret=$(($ret + 4))  ;;
-    "notice") ret=$(($ret + 5))  ;;
-    "info") ret=$(($ret + 6)) ;;
-    *) ret=$(($ret + 7)) ;;
+    "alert") ret=$((ret + 1)) ;;
+    "crit") ret=$((ret + 2))  ;;
+    "err"|"error") ret=$((ret + 3))  ;;
+    "warn"|"warning") ret=$((ret + 4))  ;;
+    "notice") ret=$((ret + 5))  ;;
+    "info") ret=$((ret + 6)) ;;
+    *) ret=$((ret + 7)) ;;
   esac
   echo "<${ret}>$*"
 }
 
 # Is it different ?
-NHLOGH=$(sha256sum $tempdir/$(basename $HLOG) | cut -d' ' -f1) 
+NHLOGH=$(sha256sum "$tempdir/$(basename "$HLOG")" | cut -d' ' -f1) 
 if [ "$NHLOGH" != "$HLOGH" ]; then
   # Fetch $HLOG0 as well
   1>&2 echo "File $HLOG different ${NHLOGH:0:10}.. (${HLOGH:0:10}..)"
-  if scp tc@$INTERCO_HAUT:$HLOG0 $tempdir/$(basename $HLOG0); then
-    NHLOGH0=$(sha256sum $tempdir/$(basename $HLOG0) | cut -d' ' -f1) 
+  if scp "tc@$INTERCO_HAUT:$HLOG0" "$tempdir/$(basename "$HLOG0")"; then
+    NHLOGH0=$(sha256sum "$tempdir/$(basename "$HLOG0")" | cut -d' ' -f1) 
     if [ "$NHLOGH0" != "$HLOGH0" ]; then
       1>&2 echo "File $HLOG0 different ${NHLOGH0:0:10}.. (${HLOGH0:0:10}..)"
       # The machine haut has rotated its logs
-      if [ "$(sha256sum $tempdir/$(basename $HLOG0) | cut -d' ' -f1)" != "$HLOGH" ]; then
+      if [ "$(sha256sum "$tempdir/$(basename "$HLOG0")" | cut -d' ' -f1)" != "$HLOGH" ]; then
         # There are lines in $HLOG0 to treat
-        dd status=none bs=1 skip=$HLOGSZ0 if=$tempdir/$(basename $HLOG0) | while read -r line; do
-          parse_pri $line
-        done | nc -w 1 -u $server 514
+        dd status=none bs=1 skip="$HLOGSZ0" if="$tempdir/$(basename "$HLOG0")" | while read -r line; do
+          parse_pri "$line"
+        done | nc -w 1 -u "$server" 514
       fi
-      HLOGH0=$NLOGH0
-      HLOGSZ0="$(stat -c%s $tempdir/$(basename $HLOG0))"
+      HLOGH0=$NHLOGH0
+      HLOGSZ0="$(stat -c%s "$tempdir/$(basename "$HLOG0")")"
       HLOGSZ=0
     fi
   fi
   # Treat the lines in $HLOG
-  dd status=none bs=1 skip=$HLOGSZ if=$tempdir/$(basename $HLOG) | while read -r line; do
-    parse_pri $line 
-  done | nc -w 1 -u $server 514
+  dd status=none bs=1 skip=$HLOGSZ if="$tempdir/$(basename "$HLOG")" | while read -r line; do
+    parse_pri "$line" 
+  done | nc -w 1 -u "$server" 514
 
   # Update the status file
-  HLOGH="$(sha256sum $tempdir/$(basename $HLOG) | cut -d' ' -f1)"
-  HLOGSZ="$(stat -c%s $tempdir/$(basename $HLOG))"
+  HLOGH="$(sha256sum "$tempdir/$(basename "$HLOG")" | cut -d' ' -f1)"
+  HLOGSZ="$(stat -c%s "$tempdir/$(basename "$HLOG")")"
   echo "$HLOG $HLOGSZ $HLOGH"
   echo "$HLOG0 $HLOGSZ0 $HLOGH0"
 fi
 
 # Remove temporary files
-/bin/rm -fr $tempdir
+/bin/rm -fr "$tempdir"
