feat: Allow logs of tasks from crontab as well

diff --git a/append/usr/local/sbin/runtask b/append/usr/local/sbin/runtask
--- a/append/usr/local/sbin/runtask
+++ b/append/usr/local/sbin/runtask
@@ -80,6 +80,7 @@ opts=""
 force=""
 clamav=0
 verbose=0
+logdir=""
 
 logfile="$LOG/dsas_verif.log"
 [ -f "$logfile" ] || ( umask 0007; touch "$logfile"; )
@@ -90,11 +91,12 @@ while [ "$#" -gt 0 ]; do
     -h|--help)
       echo "Usage: $(basename "$0")  [Options] ID"
       echo "Run verification task given by the task ID"
-      echo "     -f|--force      Force task to run"
-      echo "     -v|--verbose    Log all files verified"
-      echo "     -q|--quiet      Log only files failing to verify"
-      echo "     -c|--clamav     Get ClamAv signature files. The ID is ignored"
-      echo "     -h|--help       Print this help"
+      echo "     -f|--force        Force task to run"
+      echo "     -v|--verbose      Log all files verified"
+      echo "     -q|--quiet        Log only files failing to verify"
+      echo "     -c|--clamav       Get ClamAv signature files. The ID is ignored"
+      echo "     -l|--logdir <dir> Save task logs to this directory" 
+      echo "     -h|--help         Print this help"
       echo "ID can be the numerical order of the task or its MD5 ID"
       exit 0
       ;;
@@ -102,6 +104,7 @@ while [ "$#" -gt 0 ]; do
     -v|--verbose) verbose=1; opts="$opts -v"; ;;
     -q|--quiet) verbose=0; opts="$opts -q"; ;;
     -c|--clamav) clamav=1; opts="$opts -c"; ;;
+    -l|--logdir) verbose=1; logdir=$2; shift 1; opts="$opts -v"; ;;
     -*) opts="$opts $1"; ;;
      *) ids="$ids $1" ;;
   esac
@@ -189,20 +192,31 @@ for _id in $ids; do
   _pid=$(sudo pgrep "$_id")
   [ -n "$_pid" ] && { 1>&2 myecho "$0 task $_id is running"; continue; }
 
-  1>&2 myecho "$0 : #### Tasks started - $(date --utc) ####"
-  1>&2 myecho "$0 : #### Tasks on machine HAUT ####"
-  sudo sudo -u haut ssh "tc@$INTERCO_HAUT" "$(dirname "$0")/getfiles" $opts "$_id"
-  [ $? -eq 0 ] && sudo sudo -u haut ssh "tc@$INTERCO_HAUT" sudo sudo -u verif "$(dirname "$0")/checkfiles" $opts "$_id"
-  [ $? -eq 0 ] && 1>&2 myecho "$0 : #### Tasks on machine BAS ####"
-  [ $? -eq 0 ] && "$(dirname "$0")/getfiles" $opts "$_id"
-  [ $? -eq 0 ] && sudo sudo -u verif "$(dirname "$0")/checkfiles" $opts -o "$logfile" "$_id"
+  if [ -z "$logdir" ]; then
+    1>&2 myecho "$0 : #### Tasks started - $(date --utc) ####"
+    1>&2 myecho "$0 : #### Tasks on machine HAUT ####"
+    sudo sudo -u haut ssh "tc@$INTERCO_HAUT" "$(dirname "$0")/getfiles" $opts "$_id"
+    [ $? -eq 0 ] && sudo sudo -u haut ssh "tc@$INTERCO_HAUT" sudo sudo -u verif "$(dirname "$0")/checkfiles" $opts "$_id"
+    [ $? -eq 0 ] && 1>&2 myecho "$0 : #### Tasks on machine BAS ####"
+    [ $? -eq 0 ] && "$(dirname "$0")/getfiles" $opts "$_id"
+    [ $? -eq 0 ] && sudo sudo -u verif "$(dirname "$0")/checkfiles" $opts -o "$logfile" "$_id"
+    1>&2 myecho "$0 : #### Tasks Terminated - $(date --utc) ####"
+  else
+    mkdir -p "$logdir"
+    myecho "$0 : #### Tasks started - $(date --utc) ####" > "$logdir/$_id.log"
+    myecho "$0 : #### Tasks on machine HAUT ####"  >> "$logdir/$_id.log"
+    sudo sudo -u haut ssh "tc@$INTERCO_HAUT" "$(dirname "$0")/getfiles" $opts "$_id" 2>&1 >> "$logdir/$_id.log"
+    [ $? -eq 0 ] && sudo sudo -u haut ssh "tc@$INTERCO_HAUT" sudo sudo -u verif "$(dirname "$0")/checkfiles" $opts "$_id" 2>&1 >> "$logdir/$_id.log"
+    [ $? -eq 0 ] && myecho "$0 : #### Tasks on machine BAS ####" >> "$logdir/$_id.log"
+    [ $? -eq 0 ] && "$(dirname "$0")/getfiles" $opts "$_id" 2>&1 >> "$logdir/$_id.log"
+    [ $? -eq 0 ] && sudo sudo -u verif "$(dirname "$0")/checkfiles" $opts -o "$logfile" "$_id" 2>&1 >> "$logdir/$_id.log"
+    myecho "$0 : #### Tasks Terminated - $(date --utc) ####" >> "$logdir/$_id.log"
+  fi
 
   # Log the run date and exit status of the task
   _str=$(printf "%-26s %-16s %d" "$_id" "$(utc_date)" $?)
   grep -q "$_id" "$RUNLOG" && sed -i -e "s/^$_id.*$/$_str/" "$RUNLOG" 
   grep -q "$_id" "$RUNLOG" || echo "$_str" >> "$RUNLOG"
-
-  1>&2 myecho "$0 : #### Tasks Terminated - $(date --utc) ####"
 done
 
 # Cleanup the runlog file, removing non existant/deleted tasks
