fix: Replace use of subjectKetIdentifier as X509 fingerprint by the SHA256 of the DER. Use in signature verification

diff --git a/append/usr/local/sbin/runtask b/append/usr/local/sbin/runtask
--- a/append/usr/local/sbin/runtask
+++ b/append/usr/local/sbin/runtask
@@ -17,7 +17,7 @@ else
 fi
 
 # If on machine haut, quit, as this script is reserved for the machine bas
-[ "$TYP" == "haut" ] && { 1>&2 echo "$0: Must be run from machine bas'"; exit 1; }
+[ "$TYP" == "haut" ] && { 1>&2 echo "$0: Must be run from machine 'bas'"; exit 1; }
 
 # Créate run log file if it doesn't exist
 [ -f "$RUNLOG" ] || touch $RUNLOG
@@ -64,7 +64,7 @@ elif [ -z "$force" ]; then
       [ "$_id" == "$_idx" ] && break     
       i=$((i + 1))
     done
-    [ -z "$_idx" ] && 1>&2 echo "Task $_id not found" && continue
+    [ -z "$_idx" ] && { 1>&2 echo "Task $_id not found"; continue; }
     _run=$(xmllint --xpath "string(dsas/tasks/task[$i]/run)" $CONF)
     _last=$(cat $RUNLOG | grep $_id | cut -d' ' -f2)
     [ -z "$_last" ] || should_run $_last $_run && newids="$newids $_id" 
@@ -73,7 +73,7 @@ elif [ -z "$force" ]; then
 fi
 
 LOG="$(dirname $CONF)/dsas_verif.log"
-[ -f "$LOG" ] || (umask 0007; touch $LOG; )
+[ -f "$LOG" ] || ( umask 0007; touch $LOG; )
 chgrp verif $LOG
 
 [ -z "$ids" ] && 1>&2 myecho "$0: No tasks to run !!"
@@ -81,7 +81,7 @@ chgrp verif $LOG
 for _id in $ids; do
   # Check if task is already running and skip if not 
   _pid=$(pgrep $_id)
-  [ -n "$_pid" ] && { 1>&2 myecho "$0 task $_id is running"; continue }
+  [ -n "$_pid" ] && { 1>&2 myecho "$0 task $_id is running"; continue; }
 
   1>&2 myecho "$0: #### Tasks on machine HAUT ####"
   ssh tc@$INTERCO_HAUT sudo sudo -u haut $(dirname $0)/getfiles $opts $_id
